#!/usr/bin/env node
/**
 * tools/build-vendor.mjs — Rebuild the third-party vendor bundle FROM npm.
 *
 * Goal: make the build 100% client/-free. Nothing is fetched from any upstream
 * product at build time — every dependency is a public, attributable FOSS npm
 * package, bundled here and exposed to the engine (SystemJS) exactly the way the
 * engine expects.
 *
 * The engine (ra2web.js, repacked from src/) imports these modules through
 * SystemJS names (e.g. SystemJS.import("react")). SystemJS in use is v0.19.41,
 * whose reduceRegister_ stores NAMED System.registerDynamic() calls directly
 * into System.defined[name] immediately. So we emit one script that calls
 * System.registerDynamic(name, [], false, factory) for every module — they all
 * register. No need to replicate any bespoke webpack bridge.
 *
 * All deps are bundled in a SINGLE esbuild pass so react / react-dom share ONE
 * react instance (two react copies break react-dom with hook/context errors).
 *
 * Output:
 *   vendor/dist/vendor.bundle.js   — SystemJS modules for all npm deps
 *   vendor/dist/worker.js          — threads.js worker endpoint
 *
 * Run:  node tools/build-vendor.mjs
 */

import esbuild from "esbuild";
import { writeFileSync, mkdirSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const ROOT = resolve(__dirname, "..");
const OUT = join(ROOT, "vendor", "dist");
const THREE_SHIM = join(ROOT, "vendor", "three-shim.cjs");
mkdirSync(OUT, { recursive: true });

// ---- SystemJS-name -> npm require specifier -------------------------------
// `three` is intentionally absent: it is the global window.THREE (loaded by
// lib/three.min.js and registered by index.html). Addons (three.meshline etc.)
// ARE here and rely on the global THREE being present.
const MODULES = [
  ["react", "react"],
  ["react-dom", "react-dom"],
  ["classnames", "classnames"],
  ["three.meshline", "three.meshline"],
  ["stats.js", "stats.js"],
  ["js-logger", "js-logger"],
  ["wavefile", "wavefile"],
  ["sprintf-js", "sprintf-js"],
  ["mersenne-twister", "mersenne-twister"],
  ["pcx-js", "pcx-js"],
  ["@sentry/browser", "@sentry/browser"],
  ["threads", "threads"],
  ["detect-gpu", "detect-gpu"],
  ["liang-barsky", "liang-barsky"],
  ["file-system-access", "file-system-access"],
  ["file-system-access/lib/adapters/indexeddb", "file-system-access/lib/adapters/indexeddb"],
  ["file-system-access/lib/adapters/cache", "file-system-access/lib/adapters/cache"],
  ["fontfaceobserver", "fontfaceobserver"],
  ["@puzzl/core/lib/async/Task", "@puzzl/core/lib/async/Task"],
  ["@puzzl/core/lib/async/cancellation", "@puzzl/core/lib/async/cancellation"],
  ["@puzzl/core/lib/async/cancellation/CancellationToken", "@puzzl/core/lib/async/cancellation/CancellationToken"],
  ["@puzzl/core/lib/async/cancellation/CancellationTokenSource", "@puzzl/core/lib/async/cancellation/CancellationTokenSource"],
  ["@puzzl/core/lib/async/cancellation/OperationCanceledError", "@puzzl/core/lib/async/cancellation/OperationCanceledError"],
  ["@puzzl/core/lib/async/sleep", "@puzzl/core/lib/async/sleep"],
  ["@puzzl/core/lib/event/AsyncEventDispatcher", "@puzzl/core/lib/event/AsyncEventDispatcher"],
  ["@puzzl/core/lib/event/EventDispatcher", "@puzzl/core/lib/event/EventDispatcher"],
  ["@puzzl/core/lib/math/interval", "@puzzl/core/lib/math/interval"],
  ["@puzzl/core/lib/math/number", "@puzzl/core/lib/math/number"],
  ["@puzzl/core/lib/pattern/BoxedVar", "@puzzl/core/lib/pattern/BoxedVar"],
  ["@puzzl/core/lib/regexp", "@puzzl/core/lib/regexp"],
  ["@puzzl/core/lib/string", "@puzzl/core/lib/string"],
];

// ---- 1. Build the vendor registry as ONE bundle ---------------------------
console.log("[build-vendor] Bundling " + MODULES.length + " npm modules with esbuild...");

// CJS entry that require()s every module into a single registry object.
// Bundling together guarantees react/react-dom share one react instance.
const requires = MODULES.map(
  ([name, spec]) => `  ${JSON.stringify(name)}: require(${JSON.stringify(spec)}),`
).join("\n");
const entryCode =
  "// AUTO-GENERATED by tools/build-vendor.mjs — do not edit.\n" +
  "module.exports = {\n" + requires + "\n};\n";

const bundle = await esbuild.build({
  stdin: { contents: entryCode, resolveDir: ROOT, sourcefile: "vendor-entry.cjs", loader: "js" },
  bundle: true,
  // iife + globalName assigns the CJS module.exports (the registry) to a top-level
  // var __vendorRegistry__ which becomes a global when loaded via <script>.
  format: "iife",
  globalName: "__vendorRegistry__",
  platform: "browser",
  target: "es2018",
  minify: true,
  write: false,
  define: { "process.env.NODE_ENV": '"production"' },
  // `three` is the global window.THREE (loaded by lib/three.min.js). Bundled addons
  // (three.meshline) reference it via require("three"); alias that to a shim so esbuild
  // emits a plain property read instead of a dynamic require() that throws in browsers.
  alias: { three: THREE_SHIM },
  legalComments: "none",
});

const iife = bundle.outputFiles[0].text;

// ---- 2. Emit SystemJS registrations ---------------------------------------
// SystemJS 0.19.41 stores named registerDynamic immediately, so all register.
let out = "";
out += "/* vendor.bundle.js — rebuilt from npm by tools/build-vendor.mjs.\n";
out += "   Each System.registerDynamic exposes one FOSS npm dependency.\n";
out += "   License/attribution: see vendor/THIRD_PARTY_LICENSES.md. */\n";
out += iife + "\n";
out += "(function () {\n";
out += '  if (typeof window !== "undefined" && !window.System) {\n';
out += '    throw new Error("SystemJS not loaded before vendor bundle");\n';
out += "  }\n";
out += '  var __reg = typeof __vendorRegistry__ !== "undefined" ? __vendorRegistry__ : {};\n';
out += "  for (var __k in __reg) {\n";
out += "    (function (name, mod) {\n";
out += "      System.registerDynamic(name, [], false, function (_r, _e, module) {\n";
out += "        module.exports = mod;\n";
out += "      });\n";
out += "    })(__k, __reg[__k]);\n";
out += "  }\n";
out += "})();\n";

writeFileSync(join(OUT, "vendor.bundle.js"), out);
console.log(
  "[build-vendor] wrote vendor/dist/vendor.bundle.js (" +
    Math.round(out.length / 1024) +
    " KB, " +
    MODULES.length +
    " modules)"
);

// ---- 3. Build the worker endpoint (threads.js worker exposing stubs) --------
// The engine spawns this via `threads.spawn(new Worker("dist/worker.js"))` and
// expects decodeWav / generateVxlGeometry / compressFile. The heavy worker logic
// was never published, so the engine already falls back to main-thread impls;
// we expose stubs that reject, preserving that fallback while letting threads.js
// init succeed (no "did not call expose()" timeout).
console.log("[build-vendor] Bundling worker endpoint (vendor/worker-source.mjs)...");
const worker = await esbuild.build({
  entryPoints: [join(ROOT, "vendor", "worker-source.mjs")],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2018",
  minify: true,
  write: false,
  define: { "process.env.NODE_ENV": '"production"' },
  legalComments: "none",
});
writeFileSync(join(OUT, "worker.js"), worker.outputFiles[0].text);
console.log(
  "[build-vendor] wrote vendor/dist/worker.js (" +
    Math.round(worker.outputFiles[0].text.length / 1024) +
    " KB)"
);

console.log("[build-vendor] done.");
